version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-react-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

  nodejs:
    image: node:18-alpine
    container_name: node-service
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
